window.CREATE_QUIZ_SESSION = "CREATE_QUIZ_SESSION_SESSION";
window.CONNECT_TO_QUIZ = "CONNECT_TO_QUIZ";
window.NEXT_QUESTION = "NEXT_QUESTION";
window.ANSWERE_QUESTION = "ANSWERE_QUESTION";
window.DELETE_QUIZ_SESSION = "DELETE_QUIZ_SESSION";
window.INIT_QUIZ = "INIT_QUIZ";
window.NEW_PARTICIPANT = "NEW_PARTICIPANT";
window.UPDATED_PARTICIPANTS = "UPDATED_PARTICIPANTS";
window.ERROR_MESSAGE = "ERROR_MESSAGE";

window.currentQuestion = -1;
window.quizData;
window.participants;